spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: testpassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

