name: cd
on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리를 체크아웃한다
        uses: actions/checkout@v4
      - name: 자바를 설치한다
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: 어플리케이션을 빌드한다
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: 도커 허브에 로그인한다
        uses: docker/login-action@v3
        with:
          username: albertimkr001
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: 어플리케이션의 도커 이미지를 빌드하고 도커 허브에 푸시한다
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: albertimkr001/todo:lastest
      - name: 어플리케이션을 배포한다
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST_ADDRESS }}
          USER: ${{ secrets.HOST_USERNAME }}
          TAG: todo:lastest
        run: |
          # Private key를 파일로 생성합니다.
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # EC2 인스턴스에 SSH로 접속하여 Docker 컨테이너를 관리합니다.
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "
            sudo docker compose -f docker-compose.yml down
            sudo docker compose -f docker-compose.yml up -d
            sudo docker image prune -f
          "
